/**
 * Generates a complete Google Apps Script for syncing Supabase data
 * into a Google Sheet with 3 tabs: Inspections, Maintenance, Vehicle Summary.
 *
 * Reads NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY from env.
 * These are injected at build time by Next.js (NEXT_PUBLIC_ prefix).
 */
export function generateAppsScript(): string {
  const supabaseUrl =
    process.env.NEXT_PUBLIC_SUPABASE_URL ?? "<YOUR_SUPABASE_URL>";
  const supabaseAnonKey =
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ?? "<YOUR_SUPABASE_ANON_KEY>";

  return `// ================================================================
// State Fleet — Google Sheets Live Sync
// Auto-generated by State Fleet Admin Panel
//
// SETUP (one time):
//   1. Extensions → Apps Script → paste this file → Save (Ctrl+S)
//   2. Run onOpen() → authorize when prompted
//   3. Use the "State Fleet" menu → "Setup Auto-Refresh"
//
// REQUIREMENTS:
//   Ensure the anon role has SELECT access on the tables/views used below.
//   In Supabase SQL Editor, run:
//     grant select on inspections, maintenance to anon;
//     grant select on maintenance_vehicle_summary to anon;
//   Or add row-level security policies for anon reads.
// ================================================================

var SUPABASE_URL = '${supabaseUrl}';
var SUPABASE_ANON_KEY = '${supabaseAnonKey}';

// ----------------------------------------------------------------
// Menu
// ----------------------------------------------------------------
function onOpen() {
  SpreadsheetApp.getUi()
    .createMenu('State Fleet')
    .addItem('Refresh Now', 'refreshAll')
    .addSeparator()
    .addItem('Setup Auto-Refresh (5 min)', 'setupAutoRefresh')
    .addItem('Stop Auto-Refresh', 'stopAutoRefresh')
    .addToUi();
}

// ----------------------------------------------------------------
// Refresh all sheets
// ----------------------------------------------------------------
function refreshAll() {
  refreshInspections();
  refreshMaintenance();
  refreshVehicleSummary();
  SpreadsheetApp.getActiveSpreadsheet()
    .toast('All 3 sheets refreshed successfully!', 'State Fleet', 4);
}

// ----------------------------------------------------------------
// INSPECTIONS sheet
// ----------------------------------------------------------------
function refreshInspections() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var sheet = ss.getSheetByName('Inspections');
  if (!sheet) sheet = ss.insertSheet('Inspections');

  var data = fetchFromSupabase(
    '/rest/v1/inspections' +
    '?select=id,created_at,odometer_km,driver_name,created_by,remarks_json' +
    ',vehicles!inner(vehicle_code,brand,model,plate_number)' +
    '&is_deleted=eq.false' +
    '&order=created_at.desc' +
    '&limit=200'
  );
  if (!data) { Logger.log('refreshInspections: no data'); return; }

  sheet.clearContents();
  sheet.clearFormats();

  var headers = [
    'Date', 'Vehicle Code', 'Plate No.', 'Brand / Model',
    'Driver', 'Odometer (km)', 'Status', 'Issues', 'Created By'
  ];
  var rows = [headers];

  for (var i = 0; i < data.length; i++) {
    var row = data[i];
    var vehicle = row.vehicles || {};
    var status = getInspectionStatus(row.remarks_json);
    var issueCount = getInspectionIssueCount(row.remarks_json);
    rows.push([
      formatDate(row.created_at),
      vehicle.vehicle_code || '',
      vehicle.plate_number || '',
      ((vehicle.brand || '') + ' ' + (vehicle.model || '')).trim(),
      row.driver_name || '',
      row.odometer_km || 0,
      status,
      issueCount,
      row.created_by || ''
    ]);
  }

  if (rows.length > 1) {
    sheet.getRange(1, 1, rows.length, headers.length).setValues(rows);
  }

  styleHeaders_(sheet, headers.length);

  // Color-code Status column (col 7)
  for (var r = 2; r <= rows.length; r++) {
    var cell = sheet.getRange(r, 7);
    var val = cell.getValue();
    if (val === 'Pass') {
      cell.setBackground('#dcfce7');
      cell.setFontColor('#166534');
      cell.setFontWeight('bold');
    } else if (val === 'Issues') {
      cell.setBackground('#fee2e2');
      cell.setFontColor('#991b1b');
      cell.setFontWeight('bold');
    }
  }

  autoResizeAll_(sheet, headers.length);
  writeTimestamp_(sheet, rows.length);
}

// ----------------------------------------------------------------
// MAINTENANCE sheet
// ----------------------------------------------------------------
function refreshMaintenance() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var sheet = ss.getSheetByName('Maintenance');
  if (!sheet) sheet = ss.insertSheet('Maintenance');

  var data = fetchFromSupabase(
    '/rest/v1/maintenance' +
    '?select=id,created_at,odometer_km,bill_number,supplier_name' +
    ',supplier_invoice_number,amount,remarks,created_by' +
    ',vehicles!inner(vehicle_code,brand,model)' +
    '&is_deleted=eq.false' +
    '&order=created_at.desc' +
    '&limit=200'
  );
  if (!data) { Logger.log('refreshMaintenance: no data'); return; }

  sheet.clearContents();
  sheet.clearFormats();

  var headers = [
    'Date', 'Vehicle Code', 'Brand / Model',
    'Bill Number', 'Supplier', 'Invoice No.',
    'Amount (MYR)', 'Cost Tier', 'Odometer (km)', 'Remarks', 'Created By'
  ];
  var rows = [headers];

  for (var i = 0; i < data.length; i++) {
    var row = data[i];
    var vehicle = row.vehicles || {};
    var amount = row.amount || 0;
    rows.push([
      formatDate(row.created_at),
      vehicle.vehicle_code || '',
      ((vehicle.brand || '') + ' ' + (vehicle.model || '')).trim(),
      row.bill_number || '',
      row.supplier_name || '',
      row.supplier_invoice_number || '',
      amount,
      getCostTier(amount),
      row.odometer_km || 0,
      row.remarks || '',
      row.created_by || ''
    ]);
  }

  if (rows.length > 1) {
    sheet.getRange(1, 1, rows.length, headers.length).setValues(rows);
  }

  styleHeaders_(sheet, headers.length);

  // Color-code Cost Tier column (col 8)
  for (var r = 2; r <= rows.length; r++) {
    var cell = sheet.getRange(r, 8);
    var val = cell.getValue();
    if (val === 'Low') {
      cell.setBackground('#dcfce7');
      cell.setFontColor('#166534');
    } else if (val === 'Medium') {
      cell.setBackground('#fef9c3');
      cell.setFontColor('#854d0e');
    } else if (val === 'High') {
      cell.setBackground('#ffedd5');
      cell.setFontColor('#9a3412');
    } else if (val === 'Critical') {
      cell.setBackground('#fee2e2');
      cell.setFontColor('#991b1b');
      cell.setFontWeight('bold');
    }
  }

  autoResizeAll_(sheet, headers.length);
  writeTimestamp_(sheet, rows.length);
}

// ----------------------------------------------------------------
// VEHICLE SUMMARY sheet (from maintenance_vehicle_summary view)
// ----------------------------------------------------------------
function refreshVehicleSummary() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var sheet = ss.getSheetByName('Vehicle Summary');
  if (!sheet) sheet = ss.insertSheet('Vehicle Summary');

  var data = fetchFromSupabase('/rest/v1/maintenance_vehicle_summary?select=*');
  if (!data) { Logger.log('refreshVehicleSummary: no data'); return; }

  sheet.clearContents();
  sheet.clearFormats();

  var headers = [
    'Vehicle Code', 'Brand', 'Model', 'Plate No.',
    'Total Cost (MYR)', 'Records', 'Last Maintenance', 'Last Odometer (km)'
  ];
  var rows = [headers];

  for (var i = 0; i < data.length; i++) {
    var row = data[i];
    rows.push([
      row.vehicle_code || '',
      row.brand || '',
      row.model || '',
      row.plate_number || '',
      row.total_cost || 0,
      row.record_count || 0,
      row.last_maintenance_date ? formatDate(row.last_maintenance_date) : 'Never',
      row.last_odometer || 0
    ]);
  }

  if (rows.length > 1) {
    sheet.getRange(1, 1, rows.length, headers.length).setValues(rows);
  }

  styleHeaders_(sheet, headers.length);
  autoResizeAll_(sheet, headers.length);
  writeTimestamp_(sheet, rows.length);
}

// ----------------------------------------------------------------
// Helpers
// ----------------------------------------------------------------
function getInspectionStatus(remarksJson) {
  if (!remarksJson) return 'Pass';
  try {
    var remarks = (typeof remarksJson === 'string')
      ? JSON.parse(remarksJson)
      : remarksJson;
    for (var key in remarks) {
      if (remarks[key] && remarks[key].ok === false) return 'Issues';
    }
    return 'Pass';
  } catch (e) {
    return 'Unknown';
  }
}

function getInspectionIssueCount(remarksJson) {
  if (!remarksJson) return 0;
  try {
    var remarks = (typeof remarksJson === 'string')
      ? JSON.parse(remarksJson)
      : remarksJson;
    var count = 0;
    for (var key in remarks) {
      if (remarks[key] && remarks[key].ok === false) count++;
    }
    return count;
  } catch (e) {
    return 0;
  }
}

function getCostTier(amount) {
  if (amount < 200)  return 'Low';
  if (amount < 1000) return 'Medium';
  if (amount < 5000) return 'High';
  return 'Critical';
}

function formatDate(isoString) {
  if (!isoString) return '';
  try {
    return new Date(isoString).toLocaleDateString('en-MY');
  } catch (e) {
    return isoString;
  }
}

function styleHeaders_(sheet, numCols) {
  var range = sheet.getRange(1, 1, 1, numCols);
  range.setFontWeight('bold');
  range.setBackground('#4338ca');
  range.setFontColor('#ffffff');
  range.setFontSize(10);
}

function autoResizeAll_(sheet, numCols) {
  for (var c = 1; c <= numCols; c++) {
    sheet.autoResizeColumn(c);
  }
}

function writeTimestamp_(sheet, dataRowCount) {
  var tsRow = dataRowCount + 2;
  var cell = sheet.getRange(tsRow, 1);
  cell.setValue('Last Updated: ' + new Date().toLocaleString('en-MY'));
  cell.setFontColor('#94a3b8');
  cell.setFontStyle('italic');
  cell.setFontSize(9);
}

// ----------------------------------------------------------------
// Auto-refresh triggers
// ----------------------------------------------------------------
function setupAutoRefresh() {
  stopAutoRefresh();
  ScriptApp.newTrigger('refreshAll')
    .timeBased()
    .everyMinutes(5)
    .create();
  SpreadsheetApp.getActiveSpreadsheet()
    .toast('Auto-refresh enabled every 5 minutes.', 'State Fleet', 4);
}

function stopAutoRefresh() {
  var triggers = ScriptApp.getProjectTriggers();
  for (var i = 0; i < triggers.length; i++) {
    if (triggers[i].getHandlerFunction() === 'refreshAll') {
      ScriptApp.deleteTrigger(triggers[i]);
    }
  }
}

// ----------------------------------------------------------------
// Supabase REST fetch
// ----------------------------------------------------------------
function fetchFromSupabase(endpoint) {
  try {
    var response = UrlFetchApp.fetch(SUPABASE_URL + endpoint, {
      method: 'get',
      headers: {
        'apikey': SUPABASE_ANON_KEY,
        'Authorization': 'Bearer ' + SUPABASE_ANON_KEY,
        'Content-Type': 'application/json'
      },
      muteHttpExceptions: true
    });
    var code = response.getResponseCode();
    if (code !== 200) {
      Logger.log('Supabase HTTP ' + code + ': ' + response.getContentText());
      return null;
    }
    return JSON.parse(response.getContentText());
  } catch (e) {
    Logger.log('fetchFromSupabase error: ' + e.message);
    return null;
  }
}
`;
}
